---
- hosts: all
  become: yes
  tasks:
  - name: Install httpd on redhat 
    yum: 
      name: httpd
      state: present 
    when: ansible_os_family == "RedHat"

  - name: Install apache2 on debian
    apt:
      name: apache2
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"

  - name: Start the httpd service
    service:
      name: httpd 
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: Start the apache2 service
    service:
      name: apache2
      state: started 
      enabled: yes
    when: ansible_os_family == "Debian"
